<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0-ios;net10.0-maccatalyst;net10.0-macos</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Evergine.Metal" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ZenithEngine.Common\ZenithEngine.Common.csproj" />
    </ItemGroup>

</Project>
