public class Constants
{
    public static const float PI = 3.14159265358979323846;

    public static const float TWO_PI = 6.28318530717958647692;

    public static const float INV_PI = 0.31830988618379067154;

    public static const float INV_2PI = 0.15915494309189533577;

    public static const float EPS = 0.001;

    public static const float MINIMUM = 0.0001;

    public static const float INFINITY = 1000000.0;
}
